### ISSUE TITLE
Remove 30 day limit on sync

### ISSUE THREAD

**Issue by DieNastie** [JustArchi/ESGST#4]
I dont know when but one of the recent changes introduced a limit of syncing black/whitelist and hidden games only manually every 30 days.

Can you take a look if those 30 days can be removed? Should i possibly elaborate more?

**Comment by JustArchi** [comment]
Seems reasonable to me.

**Comment by JustArchi** [comment]
The above change will hit the userscript in approx ~15h from now. Since the userscript version didn't change (I don't want to resolve future conflicts with upstream), you'll likely need to manually force update in order to get the changes mentioned. Or wait for rafael to release new version.

Note: I didn't test this, but based on rafael's commits, that should be everything required to remove artificial limit on syncing blacklist/whitelist and hidden games.

**Comment by DieNastie** [comment]
It works now although it keeps throwing the first warning for sync being sequential, 1per second and limited to 30 days still. But the sync does go through.

Name change worked too btw.

Cheers

**Comment by JustArchi** [comment]
Yes, I keep the changes to the minimum to meet what we need, I don't want to create more conflicts than needed, glad to hear it works for you.
